name: Pull Request Test

on:
  pull_request:
    branches: [master]
   

jobs:
  comment-pull-request:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses:  actions/github-script@v6
        id: my-script
        with:
          script: |
                console.log("->",context.payload.pull_request.head.repo.full_name)
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.number,
                  body: "commentBody"
                })

