name: Pull Request Test

on:
  pull_request:
    branches: [master]
   

jobs:
  comment-pull-request:
    runs-on: ubuntu-latest
    permissions: 
     pull-requests: write
    steps:
      - uses:  actions/github-script@v6
        id: my-script
        with:
          script: |
               console.log("logging")
               console.log(context)

