name: Pull Request Test

on:
  pull_request:
    branches: [master]

jobs:
  merge-pull-request-from-bot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions: 
      pull-requests: write
      content: write
    steps:
      - name: test
        run: gh pr merge ${{github.event.pull_request.html_url}} -r -b "auto-merging dependabot PR"
        env:
         GH_TOKEN: ${{ github.token }}
