name: Pull Request Test

on:
  pull_request:
    branches: [master]
   

jobs:
  comment-pull-request:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      issues: write
      repository-projects: write
    steps:
      - name: test
        run: echo data ${{github.event.pull_request}}