name: Pull Request Test

on:
  pull_request:
    branches: [dependabot-no-pr]
   

jobs:
  comment-pull-request:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      issues: write
      repository-projects: write
    steps:
      - name: test
        run: gh pr merge ${{github.event.pull_request.html_url}} -r -b "auto-merging dependabot PR"
        env:
         GH_TOKEN: ${{ github.token }}
